project_id = "zopyyirugnourtelzelm"

[functions.dongvan-api]
verify_jwt = false

[functions.sync-products]
verify_jwt = true

[functions.expire-deposits]
verify_jwt = false

[functions.cryptomus-create]
verify_jwt = true

[functions.cryptomus-webhook]
verify_jwt = false
